# # .github/workflows/deploy.yml
# name: Deploy PR previews
# on:
#   pull_request:
#     types:
#       - opened
#       - reopened
#       - synchronize
#       - closed 
# jobs:
#   deploy-preview:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v2

#     - name: Set up Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '20.3.1'  # Set this to your Node.js version

#     - name: Install Dependencies
#       run: npm install

#     - name: Build
#       run: npm run build
#       env:
#         CI: ""
      
#     - name: Deploy PR Preview
#       uses: rossjrw/pr-preview-action@v1.4.3
#       with:
#           token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
#           preview-branch: gh-pages
#           source-dir: build
#           umbrella-dir: pr-preview
#           action: auto
#       # run: |
#       #   git config --global user.name $user_name
#       #   git config --global user.email $user_email
#       #   git remote set-url origin https://${github_token}@github.com/${repository}
#       #   npm run deploy
#       env:
#         user_name: 'github-actions[bot]'
#         user_email: 'github-actions[bot]@users.noreply.github.com'
#         github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
#         repository: ${{ github.repository }}
#         CI: ""
